"""
This type stub file was generated by pyright.
"""

class BinaryReader:
	def __init__(self, buf, endian=...) -> None:
		...
	
	def read(self, *args):
		...
	
	def seek(self, *args):
		...
	
	def tell(self):
		...
	
	def finished(self):
		...
	
	def read_string(self, maxlen=...): # -> bytes:
		...
	
	def struct_calcsize(self, fmt): # -> int:
		...
	
	def read_struct(self, fmt, endian=...): # -> Tuple[Any, ...]:
		...
	
	def read_struct_into(self, dest, fmt, endian=...):
		...
	
	def read_type(self, type_fmt, endian=...): # -> Any:
		...
	


class LibraryNotFoundException(OSError):
	...


def load_lib(*names): # -> CDLL:
	...

